layout_spectrum: 0.8777436
typography_spectrum: 0.4747891
color:
  saturation: 0.6117623
  lightness: 0.3360212
  brandStrength: 0.4279104
  rhythmicContrast: 0.9181457
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
name: LosSonidosDelViento
