collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.1409774
  brandStrength: 0.4279104
  lightness: 0.1547619
  brandColors:
    - '#08070C'
    - '#37363C'
    - '#D4BFAA'
    - '#A18C6D'
    - '#FFFCF3'
  rhythmicContrast: 0.2556391
typography_spectrum: 0.4747891
layout_spectrum: 0.8777436
name: LosSonidosDelViento
